version: '3'
services:
  app:
    build: ./docker/go
    volumes:
      - ./:/go/src/app
    ports:
      - "8002:8000"
    tty: true
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      AUTH_API_HOST: ${AUTH_API_HOST}
